// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://izapqochharyxanwsqag.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Iml6YXBxb2NoaGFyeXhhbndzcWFnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY0MDkwMTIsImV4cCI6MjA3MTk4NTAxMn0.ourvPS44yqM11lPG5EU1XHDkxst4n7XUuZeKbiOSPrc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});